### PR TITLE
Add some rainbows

### PR DESCRIPTION
**Pull request by djns99**

### CODE REVIEW

**Review by ehjc1 — APPROVED** [review]
I approve of this change!

**Comment by ZC77** [comment]
LGTM! Get this in prod ASAP! Let's get this quick win

**Review by ZC77 — APPROVED** [review]

**Comment by jesse-rb** [comment]
Perfect, just needs an `alt` tag!

**Comment by Skwangles** [comment]
I approve!

**Review by wa-bha — CHANGES_REQUESTED** [review]
Gentlemen, let's rein in our enthusiasm. While I appreciate the initiative...

- the testing 🧪 strategy is missing 
- where's the deployment plan
- this was **not** on the roadmap 🗺️  - did you even speak to the pm?

**changes REQUESTED** 😉

**Pull request closed without merging**
